name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger
  push:               # Regenerates on every push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: MananKakkar1
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate GitHub Snake SVG"
          add: 'output/*.svg'
